package cq_server.model;

public enum GameFrame {
	// START 11, 0, 0
	// PREPARE_BASES 1, 0, 0
	// BUILD_FIRST_BASE 1, 1, 3
	// BUILD_SECOND_BASE 1, 1, 3
	// BUILD_THIRD_BASE 1, 1, 3
	// PREPARE_FOR_TIPQUESTION 3, 1, 0
	// SEND_SPREADINGTIP 3, 1, 1
	// SEND_SPREADINGTIP_TIPINFO 3, 1, 2
	// SEND_SPREADINGTIP_TIPINFO_TIPRESULT 3, 1, 2
	// SEND_SPREADING_SELECTAREA_TO_WINNERTIP_1 3, 1, 4
	// SEND_SPREADING_SELECTAREA_TO_WINNERTIP_2 3, 1, 6
	// SEND_SPREADING_SELECTAREA_TO_SECONDTIP 3, 1, 8
	// SPREADINGTIP_AREAS_SELECTED 3, 1, 10
	//
	// PREPARE_FOR_BATTLE 4, 1, 0
	// SEND_SELECT_BATTLE_AREA_TO_OFFENDER 4, 1, 1
	// BATTLE_AREA_SELECTED 4, 1, 3
	// SEND_FOUROPTIONSQUESTION_TO_OFFENDER_DEFFENDER 4, 1, 4
	// SEND_FOUROPTIONSQUESTION_ANSWERRESULT 4, 1, 6
	// SEND_BATTLE_TIPQUESTION 4, 1, 10
	// SEND_BATTLE_TIPQUESTION_TIPINFO 4, 1, 11
	// SEND_BATTLE_TIPQUESTION_TIPINFO_TIPRESULT 4, 1, 12
	// DESTROY_TOWER 4, 1, 15
	// PREPARE_NEXT_LEG 4, 1, 21
	// FINISH_GAME 15, 1, 0
	//@formatter:off
	START(11, 0),
	PREPARE_BASES (1,  0),
	BUILD_FIRST_BASE (1, 3),
	BUILD_SECOND_BASE (1,  3),
	BUILD_THIRD_BASE  (1, 3),
	PREPARE_FOR_TIPQUESTION  (3,  0),
	SEND_SPREADINGTIP ( 3, 1),
	SEND_SPREADINGTIP_TIPINFO  (3, 2),
	SEND_SPREADINGTIP_TIPINFO_TIPRESULT  (3, 3),
	SEND_SPREADING_SELECTAREA_TO_WINNERTIP_1  (3, 4),
	SEND_SPREADING_SELECTAREA_TO_WINNERTIP_2  (3, 6),
	SEND_SPREADING_SELECTAREA_TO_SECONDTIP  (3,  8),
	SPREADINGTIP_AREAS_SELECTED  (3, 10), 
	NEW_BATTLE  (4, 0),
	SEND_SELECT_BATTLE_AREA_TO_OFFENDER  (4, 1),
	BATTLE_AREA_SELECTED  (4, 3),
	SEND_FOUROPTIONSQUESTION_TO_OFFENDER_DEFFENDER  (4, 4),
	SEND_FOUROPTIONSQUESTION_ANSWERRESULT  (4, 6),
	SEND_BATTLE_TIPQUESTION  (4, 10),
	SEND_BATTLETIPQUESTION_TIPINFO  (4, 11),
	SEND_BATTLETIPQUESTION_TIPINFO_TIPRESULT  (4, 12),
	DESTROY_TOWER  (4, 15),
	PREPARE_NEXT_LEG (4, 21),
	FINISH_GAME  (15, 0),
	WAITING_FOR_CLOSING(15, 1);
	//@formatter:on
	private final int state;

	private final int phase;

	private GameFrame(int state, int phase) {
		this.state = state;
		this.phase = phase;
	}

	public int getState() {
		return state;
	}

	public int getPhase() {
		return phase;
	}
}
