<LOCATION ID="1" NAME="Ain" />
<LOCATION ID="2" NAME="Aisne" />
<LOCATION ID="3" NAME="Allier" />
<LOCATION ID="4" NAME="Alpes-de-Haute-Provence" />
<LOCATION ID="5" NAME="Hautes-Alpes" />
<LOCATION ID="6" NAME="Alpes-Maritimes" />
<LOCATION ID="7" NAME="Ardèche" />
<LOCATION ID="8" NAME="Ardennes" />
<LOCATION ID="9" NAME="Ariège" />
<LOCATION ID="10" NAME="Aube" />
<LOCATION ID="11" NAME="Aude" />
<LOCATION ID="12" NAME="Aveyron" />
<LOCATION ID="13" NAME="Bouches-du-Rhône" />
<LOCATION ID="14" NAME="Calvados" />
<LOCATION ID="15" NAME="Cantal" />
<LOCATION ID="16" NAME="Charente" />
<LOCATION ID="17" NAME="Charente-Maritime" />
<LOCATION ID="18" NAME="Cher" />
<LOCATION ID="19" NAME="Corrèze" />
<LOCATION ID="20" NAME="Corse-du-Sud" />
<LOCATION ID="21" NAME="Haute-Corse" />
<LOCATION ID="22" NAME="Côte-d&#039;Or" />
<LOCATION ID="23" NAME="Côtes-d&#039;Armor" />
<LOCATION ID="24" NAME="Creuse" />
<LOCATION ID="25" NAME="Dordogne" />
<LOCATION ID="26" NAME="Doubs" />
<LOCATION ID="27" NAME="Drôme" />
<LOCATION ID="28" NAME="Eure" />
<LOCATION ID="29" NAME="Eure-et-Loir" />
<LOCATION ID="30" NAME="Finistère" />
<LOCATION ID="31" NAME="Gard" />
<LOCATION ID="32" NAME="Haute-Garonne" />
<LOCATION ID="33" NAME="Gers" />
<LOCATION ID="34" NAME="Gironde" />
<LOCATION ID="35" NAME="Hérault" />
<LOCATION ID="36" NAME="Ille-et-Vilaine" />
<LOCATION ID="37" NAME="Indre" />
<LOCATION ID="38" NAME="Indre-et-Loire" />
<LOCATION ID="39" NAME="Isère" />
<LOCATION ID="40" NAME="Jura" />
<LOCATION ID="41" NAME="Landes" />
<LOCATION ID="42" NAME="Loir-et-Cher" />
<LOCATION ID="43" NAME="Loire" />
<LOCATION ID="44" NAME="Haute-Loire" />
<LOCATION ID="45" NAME="Loire-Atlantique" />
<LOCATION ID="46" NAME="Loiret" />
<LOCATION ID="47" NAME="Lot" />
<LOCATION ID="48" NAME="Lot-et-Garonne" />
<LOCATION ID="49" NAME="Lozère" />
<LOCATION ID="50" NAME="Maine-et-Loire" />
<LOCATION ID="51" NAME="Manche" />
<LOCATION ID="52" NAME="Marne" />
<LOCATION ID="53" NAME="Haute-Marne" />
<LOCATION ID="54" NAME="Mayenne" />
<LOCATION ID="55" NAME="Meurthe-et-Moselle" />
<LOCATION ID="56" NAME="Meuse" />
<LOCATION ID="57" NAME="Morbihan" />
<LOCATION ID="58" NAME="Moselle" />
<LOCATION ID="59" NAME="Nièvre" />
<LOCATION ID="60" NAME="Nord" />
<LOCATION ID="61" NAME="Oise" />
<LOCATION ID="62" NAME="Orne" />
<LOCATION ID="63" NAME="Pas-de-Calais" />
<LOCATION ID="64" NAME="Puy-de-Dôme" />
<LOCATION ID="65" NAME="Pyrénées-Atlantiques" />
<LOCATION ID="66" NAME="Hautes-Pyrénées" />
<LOCATION ID="67" NAME="Pyrénées-Orientales" />
<LOCATION ID="68" NAME="Bas-Rhin" />
<LOCATION ID="69" NAME="Haut-Rhin" />
<LOCATION ID="70" NAME="Rhône" />
<LOCATION ID="71" NAME="Haute-Saône" />
<LOCATION ID="72" NAME="Saône-et-Loire" />
<LOCATION ID="73" NAME="Sarthe" />
<LOCATION ID="74" NAME="Savoie" />
<LOCATION ID="75" NAME="Haute-Savoie" />
<LOCATION ID="76" NAME="Paris" />
<LOCATION ID="77" NAME="Seine-Maritime" />
<LOCATION ID="78" NAME="Seine-et-Marne" />
<LOCATION ID="79" NAME="Yvelines" />
<LOCATION ID="80" NAME="Deux-Sèvres" />
<LOCATION ID="81" NAME="Somme" />
<LOCATION ID="82" NAME="Tarn" />
<LOCATION ID="83" NAME="Tarn-et-Garonne" />
<LOCATION ID="84" NAME="Var" />
<LOCATION ID="85" NAME="Vaucluse" />
<LOCATION ID="86" NAME="Vendée" />
<LOCATION ID="87" NAME="Vienne" />
<LOCATION ID="88" NAME="Haute-Vienne" />
<LOCATION ID="89" NAME="Vosges" />
<LOCATION ID="90" NAME="Yonne" />
<LOCATION ID="91" NAME="Territoire de Belfort" />
<LOCATION ID="92" NAME="Essonne" />
<LOCATION ID="93" NAME="Hauts-de-Seine" />
<LOCATION ID="94" NAME="Seine-Saint-Denis" />
<LOCATION ID="95" NAME="Val-de-Marne" />
<LOCATION ID="96" NAME="Val-d&#039;Oise" />
<LOCATION ID="97" NAME="Guadeloupe" />
<LOCATION ID="98" NAME="Martinique" />
<LOCATION ID="99" NAME="Guyane" />
<LOCATION ID="100" NAME="La Réunion" />
<LOCATION ID="101" NAME="Hors France" />
